wip
casnerano/seckeep pull request #1
Opened 2023-05-24 17:07 UTC by casnerano

2023-05-27 12:24 UTC, kilchik requested changes
По структуре: 
- shared - неговорящее название (как misc, helper и т д), думаю, идиоматично общие для клиента и сервера пакеты расположить в /pkg. Если там только модель, то можно положить в /pkg/model или /pkg/data
- в остальном структура выглядит хорошо, здорово, что есть отдельный сервисный слой

2023-05-27 12:24 UTC, kilchik commented on pkg/log/logger.go
> +// Handler используется для обработчиков логирования.
Не понял, зачем понадобился кастомный буферизующий логер? 
Если сервис сложился в середине procInterval, разработчик сможет увидеть логи?

2023-05-27 12:24 UTC, kilchik commented on internal/server/http/handler/data.go
> +		d.logger.Error("Ошибка при добавлении записи.", err.Error())
Если придет запрос от техподдержки, что пользователи жалуются, что у них не заливаются секреты, тебе потребуется по id пользователя нагрепать проблемные логи, для этого в логе должен быть весь контекст запроса, включая user_id и прочее

2023-05-27 12:24 UTC, kilchik commented on cmd/client/main.go
> +		panic(err.Error())
Приложение не должно кидать паник, даже при старте. Лучший способ обработки исключительной ситуации при старте - `log.Fatal("что пытаемся сделать: %w", err)`

2023-05-27 12:24 UTC, kilchik commented on internal/server/http/server.go
> +		if err := s.httpServer.ListenAndServe(); err != nil && err != http.ErrServerClosed {
Нужен TLS - проходили в рамках курса, довольно просто делается. У нас все-таки сервис для хранения секретов, иначе даже в зашифрованном виде данные при перехвате и краже ключа можно будет декодировать

2023-05-27 12:24 UTC, kilchik requested changes
По структуре: 
- shared - неговорящее название (как misc, helper и т д), думаю, идиоматично общие для клиента и сервера пакеты расположить в /pkg. Если там только модель, то можно положить в /pkg/model или /pkg/data
- в остальном структура выглядит хорошо, здорово, что есть отдельный сервисный слой

2023-05-27 14:53 UTC, casnerano commented on pkg/log/logger.go
> +// Handler используется для обработчиков логирования.
Хотелось добиться минимальной блокировки основного потока при логировании.
Чтобы напрямую не юзать i/o, сдел через буфер.
Если приложение убить - логи не будут видны.
Если завершили через SIGINT, SIGTERM - логи из буфера сохранятся.

2023-05-27 16:42 UTC, casnerano commented on internal/client/app.go
> +	if err := a.rootCmd.Execute(); err != nil {
Если не критично, буду в фоновом режиме делать.

2023-05-29 13:34 UTC, kilchik approved these changes

2023-05-29 13:57 UTC, merged